name: Cleanup PR Preview

on:
  pull_request:
    types: [closed]

jobs:
  cleanup:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    env:
      PR_NUMBER: ${{ github.event.pull_request.number }}
      PREVIEW_DIR: pr-${{ github.event.pull_request.number }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create empty dir
        run: |
          mkdir empty
          echo "Preview removed" > empty/index.html

      - name: Overwrite preview folder
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./empty
          destination_dir: ${{ env.PREVIEW_DIR }}
          keep_files: true
